/* regenerate the dice art and splice it into index.html + style.css */
const cp = require('child_process'), fs = require('fs'), path = require('path');
const root = path.join(__dirname, '..');
const res = cp.spawnSync('node', [path.join(__dirname, 'gen-dice.js')], { encoding: 'utf8' });
if (res.status !== 0) { console.error(res.stderr); process.exit(1); }
console.error(res.stderr);
const svg = res.stdout.split('<!-- generated by tools/gen-dice.js -->')[1].trim();

const hp = path.join(root, 'index.html');
const html = fs.readFileSync(hp, 'utf8');
const a = html.indexOf('<defs>'), b = html.indexOf('</defs>');
if (a < 0 || b < 0) throw new Error('sprite <defs> markers missing from index.html');
fs.writeFileSync(hp, html.slice(0, a + 6) + '\n' + svg + '\n  ' + html.slice(b));
console.log('spliced; sprite ' + svg.length + ' bytes');
